%3.b
clc; clear; close all;

disp('=== EJERCICIO 3 - REGRESION LINEAL ===');

disp('a) SIGNIFICADO MATEMATICO');
disp(['Modelo y terminos: El modelo de regresion lineal simple es ' ...
    'yhat = m*x + b, donde x es la variable independiente (predictora), ' ...
    'yhat es el valor predicho de la variable dependiente, m es la ' ...
    'pendiente (cuanto cambia y por cada unidad que cambia x), y b es ' ...
    'el intercepto (el valor predicho de y cuando x = 0).']);
disp(['Residual: e_i = y_i - yhat_i, la diferencia entre el valor ' ...
    'observado y_i y el valor predicho por la recta para el mismo ' ...
    'x_i. Mide que tan lejos queda cada punto de la recta ajustada.']);
disp(['Objetivo de minimos cuadrados: S(m,b) = suma_i (y_i - (m*x_i + b))^2. ' ...
    'La recta de regresion es la que minimiza esta suma de residuales ' ...
    'al cuadrado sobre todos los datos.']);
disp(['Regresion vs interpolacion: La interpolacion construye una funcion ' ...
    'que pasa exactamente por cada punto dado, mientras que la ' ...
    'regresion encuentra una unica recta que representa la tendencia ' ...
    'general de datos con ruido, sin pasar exactamente por la mayoria ' ...
    'de los puntos. La regresion se prefiere cuando los datos tienen ' ...
    'ruido de medicion, ya que forzar un ajuste exacto reproduciria el ' ...
    'ruido en lugar de la tendencia real.']);
disp('Fuente: Simple Linear Regression, ANU Systems Toolkit | https://users.cecs.anu.edu.au/~u3951377/systems_toolkit/060_data_analysis/simple_linear_regression/');
disp(' ');

disp('b) APLICACION 1');
disp('Aplicacion: Estimacion de precios de vivienda');
disp('x y unidad: area de la casa, en pies cuadrados (ft^2)');
disp('y y unidad: precio de venta de la casa, en dolares (USD)');
disp(['Que estima: cuanto tiende a aumentar el precio de venta de una ' ...
    'casa por cada pie cuadrado adicional de area, permitiendo una ' ...
    'prediccion aproximada del precio para una casa de tamano dado.']);
disp(['Una limitacion: el precio tambien depende de otros factores no ' ...
    'incluidos en el modelo, como la ubicacion, el numero de ' ...
    'habitaciones y el estado de la propiedad, por lo que las ' ...
    'predicciones basadas solo en el area pueden ser inexactas.']);
disp('Fuente: Simple Linear Regression for salary prediction example, Dallard Tech Courses | https://courses.dallard.tech/ml/notebooks/CODE_Regression_lineaire_simple');
disp(' ');

disp('b) APLICACION 2');
disp('Aplicacion: Pronostico de ventas segun gasto en publicidad');
disp('x y unidad: gasto mensual en publicidad, en dolares (USD)');
disp('y y unidad: ingresos mensuales por ventas, en dolares (USD)');
disp(['Que estima: el incremento esperado en los ingresos por ventas ' ...
    'asociado a un dolar adicional invertido en publicidad, usado ' ...
    'para pronosticar ventas futuras dado un presupuesto planeado.']);
disp(['Una limitacion: la relacion entre publicidad y ventas rara vez es ' ...
    'perfectamente lineal y puede verse afectada por estacionalidad, ' ...
    'acciones de la competencia y rendimientos decrecientes a niveles ' ...
    'altos de gasto, factores que el modelo simple no captura.']);
disp('Fuente: What is Simple Linear Regression, DEV Community | https://dev.to/dev_patel_35864ca1db6093c/what-is-simple-linear-regression-2a6m');